### ISSUE TITLE
DRAM-setup.py prepare databases error "returned non-zero exit status 4."

### ISSUE THREAD

**Issue by Edward-Tristan** [WrightonLabCSU/DRAM#112]
Hi Mike,
I'm looking forward to using DRAM, but I'm having an issue at the 'DRAM-setup.py prepare_databases' step. I hope I'm not missing something simple on my end. I am running in a conda environment. Happy to provide any other information you might need.

Thanks!

Edward

See below:

(viral-id-sop) [huqy@login1 ~]$ DRAM-setup.py prepare_databases --skip_uniref --output_dir db-dramv --threads 10
2021-09-04 12:54:12.702655: Database preparation started
1:20:48.928768: PFAM database processed
1:21:03.693863: dbCAN database processed
1:21:43.486881: RefSeq viral database processed
1:23:06.475875: MEROPS database processed
1:26:02.495055: VOGdb database processed
1:31:44.794184: KOfam database processed
1:31:47.768151: KOfam ko list processed
1:31:53.096081: PFAM hmm dat processed
1:31:55.094837: dbCAN fam activities processed
1:31:57.080159: VOGdb annotations processed
Traceback (most recent call last):
  File "/public/home/huqy/miniconda3/envs/viral-id-sop/bin/DRAM-setup.py", line 146, in <module>
    args.func(**args_dict)
  File "/public/home/huqy/miniconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 496, in prepare_databases
    output_dbs['genome_summary_form_loc'] = download_and_process_genome_summary_form(temporary, branch, verbose)
  File "/public/home/huqy/miniconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 268, in download_and_process_genome_summary_form
    download_file('https://raw.githubusercontent.com/shafferm/DRAM/%s/data/genome_summary_form.tsv' % branch,
  File "/public/home/huqy/miniconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/utils.py", line 28, in download_file
    run_process(['wget', '-O', output_file, url], verbose=verbose)
  File "/public/home/huqy/miniconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/utils.py", line 39, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/public/home/huqy/miniconda3/envs/viral-id-sop/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['wget', '-O', 'db-dramv/database_files/genome_summary_form.20210904.tsv', 'https://raw.githubusercontent.com/shafferm/DRAM/master/data/genome_summary_form.tsv']' returned non-zero exit status 4.

**Comment by rmFlynn** [comment]
Hi Edward,
Could you try running `wget -O db-dramv/database_files/genome_summary_form.20210904.tsv https://raw.githubusercontent.com/shafferm/DRAM/master/data/genome_summary_form.tsv` in the same directory and see what the result is?

**Comment by Dorothydu12** [comment]
Hi Mike,
This error also occurred when I set up database, and I ran wget -O db-dramv/database_files/genome_summary_form.20210904.tsv https://raw.githubusercontent.com/shafferm/DRAM/master/data/genome_summary_form.tsv in the same directory and it showed  "./database_files/genome_summary_form.20210904.tsv: No such file or directory"
How should I do with this error?

Thanks,
Dorothy

**Comment by rmFlynn** [comment]
Try `wget -O genome_summary_form.20210904.tsv https://raw.githubusercontent.com/shafferm/DRAM/master/data/genome_summary_form.tsv` I just want to see if you can download the file. If that works, run the setup again with the `--verbose` argument.

**Comment by Dorothydu12** [comment]
> Try `wget -O genome_summary_form.20210904.tsv https://raw.githubusercontent.com/shafferm/DRAM/master/data/genome_summary_form.tsv` I just want to see if you can download the file. If that works, run the setup again with the `--verbose` argument.

Hi Mike,

Another error occurs as below:

sqlite3.IntegrityError: UNIQUE constraint failed: viral_description.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/bin/DRAM-setup.py", line 146, in <module>
    args.func(**args_dict)
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 526, in prepare_databases
    set_database_paths(**output_dbs, use_current_locs=False, update_description_db=True, start_time=start_time)
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 354, in set_database_paths
    populate_description_db(description_db_loc, db_dict, start_time)
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 398, in populate_description_db
    add_to_description_db(db_dict['viral'], 'viral_description', make_header_dict_from_mmseqs_db,
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 314, in add_to_description_db
    db_handler.add_descriptions_to_database(description_list, name, clear_table=True)
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_handler.py", line 27, in add_descriptions_to_database
    self.session.bulk_save_objects([description_class(**i) for i in description_list])
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3589, in bulk_save_objects
    self._bulk_save_mappings(
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3805, in _bulk_save_mappings
    transaction.rollback(_capture_exception=True)
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3793, in _bulk_save_mappings
    persistence._bulk_insert(
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 104, in _bulk_insert
    _emit_insert_statements(
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1094, in _emit_insert_statements
    c = connection._execute_20(
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1611, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1478, in _execute_clauseelement
    ret = self._execute_context(
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    self._handle_dbapi_exception(
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2023, in _handle_dbapi_exception
    util.raise_(
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1779, in _execute_context
    self.dialect.do_executemany(
  File "/disk/rdisk10/shicongdu2/Tools/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 714, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: viral_description.id
[SQL: INSERT INTO viral_description (id, description) VALUES (?, ?)]
[parameters: (('YP_009137150.1', 'YP_009137150.1 neurovirulence protein ICP34.5 [Human alphaherpesvirus 2]'), ('YP_009137182.1', 'YP_009137182.1 DNA polymerase catalytic subunit [Human alphaherpesvirus 2]'), ('YP_009137214.1', 'YP_009137214.1 virion protein US2 [Human alphaherpesvirus 2]'), ('NP_042021.1', 'NP_042021.1 phosphoprotein [Borna disease virus 1]'), ('YP_009237269.1', 'YP_009237269.1 RNA-dependent RNA polymerase [Fig mosaic emaravirus]'), ('YP_006347585.1', 'YP_006347585.1 C protein [Nariva virus]'), ('YP_006390058.1', 'YP_006390058.1 HC-Pro [Hippeastrum mosaic virus]'), ('YP_006393283.1', 'YP_006393283.1 replication protein [Human papillomavirus 135]')  ... displaying 10 of 6572 total bound parameter sets ...  ('YP_009337754.1', 'YP_009337754.1 hypothetical protein 3 [Wenzhou crab virus 4]'), ('YP_009337734.1', 'YP_009337734.1 hypothetical protein 1 [Wenling sobemo-like virus 2]'))]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

**Comment by rmFlynn** [comment]
This error was last seen in [issue 58](https://github.com/shafferm/DRAM/issues/58), the solution here is the same. You should re-install dram from scratch, new environment new working directory. This is a problem with the SQL db which could be from a corrupt file or from the database being setup incorrectly. A new install should fix this error. I would keep running with the --verbose flag, just in case you run into more errors.

**Comment by Dorothydu12** [comment]
> This error was last seen in [issue 58](https://github.com/shafferm/DRAM/issues/58), the solution here is the same. You should re-install dram from scratch, new environment new working directory. This is a problem with the SQL db which could be from a corrupt file or from the database being setup incorrectly. A new install should fix this error. I would keep running with the --verbose flag, just in case you run into more errors.

Hi Mike,

I have re-installed 3 times and unfortunately this error still occurred.

**Comment by rmFlynn** [comment]
Any luck with the pearl script suggested in issue 58? I'm AFK at the moment or I give you the link myself.

**Comment by Dorothydu12** [comment]
How I could do anything with “viral.merged.protein.faa.gz” to avoid this error or any other suggestions?


Thanks a lot !


Dorothy
| |
dscdorothy
|
|
***@***.***
|
签名由网易邮箱大师定制


On 10/2/2021 11:40，Rory M ***@***.***> wrote：

Any luck with the pearl script suggested in issue 58? I'm AFK at the moment or I give you the link myself.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Dorothydu12** [comment]
> Any luck with the pearl script suggested in issue 58? I'm AFK at the moment or I give you the link myself.

I re-installed using provided pipeline, it works.

Thanks!

**Comment by rmFlynn** [comment]
Sorry for the late reply. It once again looks like wget is failing. It is not clear why, but probably it is a security measure implemented on your server related to your server. If you can fined the file `wget-log.3` it may have more info. Again, if you can't download it on the server with the wget command, you will need to download it else where and upload it. In this case point to the download gz with the `--viral_loc` command. Remember that you can see all the options with --help.

**Comment by Edward-Tristan** [comment]
> Sorry for the late reply. It once again looks like wget is failing. It is not clear why, but probably it is a security measure implemented on your server. You may want to talk to your IT department. If you can fined the file `wget-log.3` it may have more info. Again, if you can't download it on the server with the wget command, you will need to download it else where and upload it. In this case point to the download gz with the `--viral_loc` command. Remember that you can see all the options with --help.

Hi rmFlynn,
I use a different servers to set up dram and it seems work, but I use nohup 'command' & (nohup DRAM-setup.py prepare_databases --output_dir DRAM_data --skip_uniref --threads 25 &) to run the set up. The process is running almost two days, and it's still running. Is that using the nohup command will cause the process to run forever? Should I delete the nohup? But how do I continue my process while removing the role of nohup command?

**Comment by rmFlynn** [comment]
DRAM runs for a long time, 2 days could be reasonable in some cases. All the same, you should use screen or tmux before nohup, and you should use slurm or similar before those. Check your log with tail and see if dram is still working. If you did not make a log, It looks like you did not, then check that your output folder is still seeing activity. If all else fails, then you may need to re-attach to your nohup job. You can find instructions to do that online. If the job is hanging, and you can't see the output or figure out why, kill it and run it again in a screen session.

**Comment by Edward-Tristan** [comment]
> DRAM runs for a long time, 2 days could be reasonable in some cases. All the same, you should use screen or tmux before nohup, and you should use slurm or similar before those. Check your log with tail and see if dram is still working. If you did not make a log, It looks like you did not, then check that your output folder is still seeing activity. If all else fails, then you may need to re-attach to your nohup job. You can find instructions to do that online. If the job is hanging, and you can't see the output or figure out why, kill it and run it again in a screen session.

Hi rmFlynn,
Thank you for your quick reply. This time the process is going further long than before, but it still has some issues. Here is below:

2021-11-03 10:10:31.200590: Database preparation started
1:53:55.333014: PFAM database processed
1:54:14.360185: dbCAN database processed
1:59:18.617510: RefSeq viral database processed
2:02:08.865337: MEROPS database processed
2:05:28.918471: VOGdb database processed
1 day, 19:48:18.811369: KOfam database processed
1 day, 19:48:25.095023: KOfam ko list processed
1 day, 19:48:30.666598: PFAM hmm dat processed
1 day, 19:48:33.220182: dbCAN fam activities processed
1 day, 19:48:34.820503: VOGdb annotations processed
1 day, 20:01:46.878130: DRAM databases and forms downloaded
1 day, 20:01:46.881636: Files moved to final destination
1 day, 20:01:46.881690: Setting database paths
1 day, 20:01:46.881868: Database locations added to CONFIG
1 day, 20:01:46.935238: Database connection established
1 day, 20:01:46.935250: KEGG descriptions added to description database
1 day, 20:01:46.935253: UniRef descriptions added to description database
1 day, 20:01:47.385666: PFAM descriptions added to description database
1 day, 20:01:47.397046: dbCAN descriptions added to description database
Traceback (most recent call last):
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1779, in _execute_context
    self.dialect.do_executemany(
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 714, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: viral_description.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/DRAM/bin/DRAM-setup.py", line 146, in <module>
    args.func(**args_dict)
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 526, in prepare_databases
    set_database_paths(**output_dbs, use_current_locs=False, update_description_db=True, start_time=start_time)
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 354, in set_database_paths
    populate_description_db(description_db_loc, db_dict, start_time)
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 398, in populate_description_db
    add_to_description_db(db_dict['viral'], 'viral_description', make_header_dict_from_mmseqs_db,
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 314, in add_to_description_db
    db_handler.add_descriptions_to_database(description_list, name, clear_table=True)
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_handler.py", line 27, in add_descriptions_to_database
    self.session.bulk_save_objects([description_class(**i) for i in description_list])
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3590, in bulk_save_objects
    self._bulk_save_mappings(
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3806, in _bulk_save_mappings
    transaction.rollback(_capture_exception=True)
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3794, in _bulk_save_mappings
    persistence._bulk_insert(
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 106, in _bulk_insert
    _emit_insert_statements(
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1096, in _emit_insert_statements
    c = connection._execute_20(
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1611, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1478, in _execute_clauseelement
    ret = self._execute_context(
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    self._handle_dbapi_exception(
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2023, in _handle_dbapi_exception
    util.raise_(
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1779, in _execute_context
    self.dialect.do_executemany(
  File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 714, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: viral_description.id
[SQL: INSERT INTO viral_description (id, description) VALUES (?, ?)]
[parameters: (('YP_009137150.1', 'YP_009137150.1 neurovirulence protein ICP34.5 [Human alphaherpesvirus 2]'), ('YP_009137182.1', 'YP_009137182.1 DNA polymerase catalytic subunit [Human alphaherpesvirus 2]'), ('YP_009137214.1', 'YP_009137214.1 virion protein US2 [Human alphaherpesvirus 2]'), ('NP_042021.1', 'NP_042021.1 phosphoprotein [Borna disease virus 1]'), ('YP_009237269.1', 'YP_009237269.1 RNA-dependent RNA polymerase [Fig mosaic emaravirus]'), ('YP_006347585.1', 'YP_006347585.1 C protein [Nariva virus]'), ('YP_006390058.1', 'YP_006390058.1 HC-Pro [Hippeastrum mosaic virus]'), ('YP_006393283.1', 'YP_006393283.1 replication protein [Human papillomavirus 135]')  ... displaying 10 of 13628 total bound parameter sets ...  ('YP_009094389.1', 'YP_009094389.1 N protein [Puerto Almendras virus]'), ('YP_008492950.1', 'YP_008492950.1 protein U4 [Suid betaherpesvirus 2]'))]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

**Comment by Edward-Tristan** [comment]
> DRAM runs for a long time, 2 days could be reasonable in some cases. All the same, you should use screen or tmux before nohup, and you should use slurm or similar before those. Check your log with tail and see if dram is still working. If you did not make a log, It looks like you did not, then check that your output folder is still seeing activity. If all else fails, then you may need to re-attach to your nohup job. You can find instructions to do that online. If the job is hanging, and you can't see the output or figure out why, kill it and run it again in a screen session.

Hi rmFlynn,
Thank you for your quick reply. This time the process is going further long than before, but it still has some issues. Here is below:

2021-11-03 10:10:31.200590: Database preparation started
1:53:55.333014: PFAM database processed
1:54:14.360185: dbCAN database processed
1:59:18.617510: RefSeq viral database processed
2:02:08.865337: MEROPS database processed
2:05:28.918471: VOGdb database processed
1 day, 19:48:18.811369: KOfam database processed
1 day, 19:48:25.095023: KOfam ko list processed
1 day, 19:48:30.666598: PFAM hmm dat processed
1 day, 19:48:33.220182: dbCAN fam activities processed
1 day, 19:48:34.820503: VOGdb annotations processed
1 day, 20:01:46.878130: DRAM databases and forms downloaded
1 day, 20:01:46.881636: Files moved to final destination
1 day, 20:01:46.881690: Setting database paths
1 day, 20:01:46.881868: Database locations added to CONFIG
1 day, 20:01:46.935238: Database connection established
1 day, 20:01:46.935250: KEGG descriptions added to description database
1 day, 20:01:46.935253: UniRef descriptions added to description database
1 day, 20:01:47.385666: PFAM descriptions added to description database
1 day, 20:01:47.397046: dbCAN descriptions added to description database
Traceback (most recent call last):
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1779, in _execute_context
self.dialect.do_executemany(
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 714, in do_executemany
cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: viral_description.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/root/miniconda3/envs/DRAM/bin/DRAM-setup.py", line 146, in
args.func(**args_dict)
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 526, in prepare_databases
set_database_paths(**output_dbs, use_current_locs=False, update_description_db=True, start_time=start_time)
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 354, in set_database_paths
populate_description_db(description_db_loc, db_dict, start_time)
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 398, in populate_description_db
add_to_description_db(db_dict['viral'], 'viral_description', make_header_dict_from_mmseqs_db,
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 314, in add_to_description_db
db_handler.add_descriptions_to_database(description_list, name, clear_table=True)
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_handler.py", line 27, in add_descriptions_to_database
self.session.bulk_save_objects([description_class(**i) for i in description_list])
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3590, in bulk_save_objects
self._bulk_save_mappings(
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3806, in bulk_save_mappings
transaction.rollback(capture_exception=True)
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in exit
compat.raise(
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise
raise exception
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3794, in _bulk_save_mappings
persistence._bulk_insert(
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 106, in _bulk_insert
_emit_insert_statements(
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1096, in _emit_insert_statements
c = connection._execute_20(
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1611, in _execute_20
return meth(self, args_10style, kwargs_10style, execution_options)
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
return connection._execute_clauseelement(
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1478, in _execute_clauseelement
ret = self._execute_context(
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
self.handle_dbapi_exception(
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2023, in handle_dbapi_exception
util.raise(
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise
raise exception
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1779, in _execute_context
self.dialect.do_executemany(
File "/root/miniconda3/envs/DRAM/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 714, in do_executemany
cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: viral_description.id
[SQL: INSERT INTO viral_description (id, description) VALUES (?, ?)]
[parameters: (('YP_009137150.1', 'YP_009137150.1 neurovirulence protein ICP34.5 [Human alphaherpesvirus 2]'), ('YP_009137182.1', 'YP_009137182.1 DNA polymerase catalytic subunit [Human alphaherpesvirus 2]'), ('YP_009137214.1', 'YP_009137214.1 virion protein US2 [Human alphaherpesvirus 2]'), ('NP_042021.1', 'NP_042021.1 phosphoprotein [Borna disease virus 1]'), ('YP_009237269.1', 'YP_009237269.1 RNA-dependent RNA polymerase [Fig mosaic emaravirus]'), ('YP_006347585.1', 'YP_006347585.1 C protein [Nariva virus]'), ('YP_006390058.1', 'YP_006390058.1 HC-Pro [Hippeastrum mosaic virus]'), ('YP_006393283.1', 'YP_006393283.1 replication protein [Human papillomavirus 135]') ... displaying 10 of 13628 total bound parameter sets ... ('YP_009094389.1', 'YP_009094389.1 N protein [Puerto Almendras virus]'), ('YP_008492950.1', 'YP_008492950.1 protein U4 [Suid betaherpesvirus 2]'))]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

**Comment by Jibowe** [comment]
> Sorry for the delay. You should specify the location of the genome_summary_form with the `--genome_summary_form_loc` argument, so your command would be
> 
> ```
> DRAM-setup.py prepare_databases \
>     --verbose \
>     --genome_summary_form_loc /path/to/genome_summary_form \
>     --skip_uniref \
>     --output_dir db-dramv
> ```

Hi,
I have installed DRAM via Bioconda using command line conda install DRAM.

After installation, I am trying to set up DRAM via DRAM-setup.py prepare_databases --output_dir DRAM_data. There are same problems that happened: DRAM-setup.py prepare databases error "returned non-zero exit status 4. Then I tried wget -O /home/xbb/miniconda3/envs/DRAM/DRAMdata/database_files/genome_summary_form.tsv https://github.com/shafferm/DRAM/tree/master/data/genome_summary_form.tsv   and   DRAM-setup.py prepare_databases --verbose --genome_summary_form_loc /home/xbb/miniconda3/envs/DRAM/DRAMdata/database_files/genome_summary_form.tsv --output_dir /home/xbb/miniconda3/envs/DRAM/DRAMdata.  But it yet shows ：  FileExistsError: [Errno 17] File exists: '/home/xbb/miniconda3/envs/DRAM/DRAMdata/database_files'.

**Comment by rmFlynn** [comment]
@Jibowe  It looks like you need to clean up the files from your failed build. Or work from a new directory.

**Comment by rmFlynn** [comment]
@Edward-Tristan Were you able to get dram installed? Sorry, sometimes things get buried and i miss them. If you are still dealing with this issue you can use the parse_viral.pl script from https://github.com/mw55309/DRAM_hacks to trouble shoot the viral DB issue #58. Let me know if that helps.

**Comment by Jibowe** [comment]
> @Jibowe It looks like you need to clean up the files from your failed build. Or work from a new directory.

Hi,
Thanks for your advice. I tried working from a new directory and started again to set up DRAM. But  there are still same problems that happened： FileExistsError: [Errno 17] File exists: '/home/xbb/miniconda3/envs/DRAM/DRAMdata/database_files'.
I really wonder which step was wrong.

**Comment by rmFlynn** [comment]
Hmm the file `/home/xbb/miniconda3/envs/DRAM/DRAMdata` need not exist and `/home/xbb/miniconda3/envs/DRAM/DRAMdata/database_file` definitely should not exist before you run DRAM setup. Can you show the full pipeline from downloading `genome_summary_form` to running dram setup, I can emulate the error and solve it on my end. For example this at least gets to the point of downloading Pfam-A.full.gz:
```
mkdir new_directory
cd new_directory
 wget -O genome_summary_form.20210904.tsv https://raw.githubusercontent.com/shafferm/DRAM/master/data/genome_summary_form.tsv
DRAM-setup.py prepare_databases \
    --verbose \
    --genome_summary_form_loc  genome_summary_form.20210904.tsv\
    --skip_uniref \
    --output_dir my_dram_db
```
Do any dbs get downloaded before the run fails?

**Comment by Lumc46** [comment]
Hi,
My name is Lucia and I have a similar problem, but I think that it is related with the KEGG database. Since I do not have access to it I installed DRAMv database as recommended in viral-id-sop protocol (since I am working in the "viral-id-sop" conda environment):

DRAM-setup.py prepare_databases --skip_uniref --output_dir db-dramv

2022-03-03 11:22:48.365545: Database preparation started
Downloading dbCAN family activities from : https://bcb.unl.edu/dbCAN2/download/Databases/V10/CAZyDB.07292021.fam-activities.txt
Downloading dbCAN from: http://bcb.unl.edu/dbCAN2/download/dbCAN-HMMdb-V10.txt
0:00:10.710358: dbCAN database processed
0:33:50.115103: PFAM database processed
0:34:02.745791: RefSeq viral database processed
0:34:40.781921: MEROPS database processed
0:35:27.165484: VOGdb database processed
0:39:50.204444: KOfam database processed
0:39:53.938748: KOfam ko list processed
0:39:53.938785: PFAM hmm dat processed
0:39:53.938793: dbCAN fam activities processed
0:39:54.171064: VOGdb annotations processed
0:39:56.056396: DRAM databases and forms downloaded
0:39:56.060994: Files moved to final destination
/home/emm4/anaconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/database_handler.py:52: UserWarning: Database does not exist at path /home/0.Databases/db-dramv/description_db.sqlite
  warnings.warn('Database does not exist at path %s' % self.description_loc)
Traceback (most recent call last):
  File "/home/emm4/anaconda3/envs/viral-id-sop/bin/DRAM-setup.py", line 158, in <module>
    args.func(**args_dict)
  File "/home/emm4/anaconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/database_processing.py", line 374, in prepare_databases
    db_handler.populate_description_db(output_dbs['description_db_loc'], update_config=False)
  File "/home/emm4/anaconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/database_handler.py", line 231, in populate_description_db
    self.add_descriptions_to_database(self.make_header_dict_from_mmseqs_db(self.db_locs['kegg']), 'kegg_description',
  File "/home/emm4/anaconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/database_handler.py", line 154, in make_header_dict_from_mmseqs_db
    mmseqs_headers_handle = open('%s_h' % mmseqs_db, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'kegg.20220120.mmsdb_h'

At the beginning I did not give importance to it since I have not access to KEGG. But as soons as I try to annotate my data with DRAMv I have the following error:

 DRAM-v.py annotate -i test-out/for-dramv/final-viral-combined-for-dramv.fa -v test-out/for-dramv/viral-affi-contigs-for-dramv.tab -o dramv-annotate --skip_trnascan --threads 28                                
 2022-03-03 13:01:18.142842: Viral annotation started
0:00:00.359166: Retrieved database locations and descriptions
0:00:00.359217: Annotating final-viral-combined-for-dramv
0:01:53.847855: Turning genes from prodigal to mmseqs2 db
0:01:54.752503: Getting forward best hits from kegg
Traceback (most recent call last):
  File "/home/emm4/anaconda3/envs/viral-id-sop/bin/DRAM-v.py", line 153, in <module>
    args.func(**args_dict)
  File "/home/emm4/anaconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/annotate_vgfs.py", line 473, in annotate_vgfs
    annotations = annotate_fastas(contig_locs, output_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/home/emm4/anaconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 1008, in annotate_fastas
    annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_handler, min_contig_size, prodigal_mode, trans_table,
  File "/home/emm4/anaconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 916, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_handler, tmp_dir, start_time, custom_db_locs, custom_hmm_locs,
  File "/home/emm4/anaconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 778, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_handler.db_locs['kegg'], tmp_dir,
  File "/home/emm4/anaconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 666, in do_blast_style_search
    forward_hits = get_best_hits(query_db, target_db, working_dir, 'gene', db_name, bit_score_threshold,
  File "/home/emm4/anaconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 67, in get_best_hits
    run_process(['mmseqs', 'search', query_db, target_db, query_target_db, tmp_dir, '--threads', str(threads)],
  File "/home/emm4/anaconda3/envs/viral-id-sop/lib/python3.8/site-packages/mag_annotator/utils.py", line 27, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/home/emm4/anaconda3/envs/viral-id-sop/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'search', 'dramv-annotate/working_dir/final-viral-combined-for-dramv/tmp/gene.mmsdb', 'kegg.20220120.mmsdb', 'dramv-annotate/working_dir/final-viral-combined-for-dramv/tmp/gene_kegg.mmsdb', 'dramv-annotate/working_dir/final-viral-combined-for-dramv/tmp/tmp', '--threads', '28']' returned non-zero exit status 1.

So I guess that DRAMv "believes" that has to use KEGG but I cannot download it. Any idea how can I solve it? Is there anyway to indicate DRAMv that it has to skip KEGG database? I have tried to remove the environment, download the DRAM database with different commands (DRAM-setup.py prepare_databases --output_dir DRAM_data -recommended at DRAM GitHub webpage) but it always ends up with the same result.

Thank you very much for your time!

Lucia

Additional info:

DRAM-setup.py print_config
Processed search databases
KEGG db: kegg.20220120.mmsdb
KOfam db: kofam_profiles.hmm
KOfam KO list: kofam_ko_list.tsv
UniRef db: uniref90.20220219.mmsdb
Pfam db: pfam.mmspro
dbCAN db: dbCAN-HMMdb-V10.txt
RefSeq Viral db: refseq_viral.20220219.mmsdb
MEROPS peptidase db: peptidases.20220219.mmsdb
VOGDB db: vog_latest_hmms.txt

Descriptions of search database entries
Pfam hmm dat: Pfam-A.hmm.dat.gz
dbCAN family activities: CAZyDB.07292021.fam-activities.txt
VOG annotations: vog_annotations_latest.tsv.gz

Description db: /home/0.Databases/db-dramv/description_db.sqlite

DRAM distillation sheets
Genome summary form: genome_summary_form.20220219.tsv
Module step form: module_step_form.20220219.tsv
ETC module database: etc_mdoule_database.20220219.tsv
Function heatmap form: function_heatmap_form.20220219.tsv
AMG database: amg_database.20220219.tsv

**Comment by rmFlynn** [comment]
This is a bug I introduced and will be finally fixing today after it was raised in issue 152. In your case, make a file with any name, `fix.txt` for example open it with your favorite text editor and put in this line:
```
{"description_db": "None", "kegg": null, "kofam": null, "kofam_ko_list": null, "uniref": null, "pfam": null, "pfam_hmm_dat": null, "dbcan": null, "dbcan_fam_activities": null, "viral": null, "peptidase": null, "vogdb": null, "vog_annotations": null, "genome_summary_form": null, "module_step_form": null, "etc_module_database": null, "function_heatmap_form": null, "amg_database": null}
```
Then run `DRAM-setup.py import_config --config_loc fix.txt`, and run `DRAM-setup.py prepare_databases --skip_uniref --output_dir db-dramv` again. This should solve your problem.

**Comment by Lumc46** [comment]
Thank you very much Rory! It worked perfectly.
